name: "Deploy Gh Pages"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.email "contacto@primsoft.cl"
          git config --global user.name "PrimSoft SPA"

      # Set up GitHub token for authentication
      - name: Set up GitHub token for authentication
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Setup Node Js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Create CNAME file
        run: echo "primsoft.cl" > ./dist/CNAME

      - name: Deploy to Gh Pages
        run: npm run deploy